# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Google-Oriented Programmer
email: guodong000@gmail.com
description:
  Where I write about technical and other awesome things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guodong.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: guodong000
github_username:  guodong000

# Build settings
timezone: Asia/Shanghai
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

theme: no-style-please
remote_theme: no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "< Back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
